import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => (
  <html lang="en">
    <body className={inter.className}>{children}</body>
  </html>
);

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default RootLayout;
